name: parallel-jobs
on:
  push:
  schedule:
    - cron: '0 6 * * *'

jobs:
  prepare:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to kio.ee
        run: cat /srv/base-images/config | docker login --username robot+base+builder --password-stdin
  edge:
    needs: prepare
    runs-on: self-hosted
    steps:
      - name: Make ABI Edge Image
        run: zsh make-edge-image.sh
        working-directory: ./abi/edge
  runtime:
    needs: edge
    runs-on: self-hosted
    steps:
      - name: Make ABI Runtime Image
        run: zsh make-runtime-image.sh
        working-directory: ./abi/runtime
  go:
    needs: edge
    runs-on: self-hosted
    steps:
      - name: Make Go Image
        run: zsh make-go-image.sh
        working-directory: ./go/1.18
  jdk:
    needs: edge
    runs-on: self-hosted
    steps:
      - name: Make JDK Image
        run: zsh make-jdk-image.sh
        working-directory: ./java/17/jdk
  jre:
    needs: runtime
    runs-on: self-hosted
    steps:
      - name: Make JRE Image
        run: zsh make-jre-image.sh
        working-directory: ./java/17/jre
