name: build-base-images
on:
  push:
  schedule:
    - cron: '0 3 * * *'

jobs:
  prepare:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to kio.ee
        run: cat /srv/base-images/config | docker login --username robot+base+builder --password-stdin kio.ee
      - name: Make build clean
        run: docker system prune --all -f
  edge:
    needs: prepare
    runs-on: self-hosted
    steps:
      - name: Make ABI Edge Image
        run: zsh -x make-edge-image.sh
        working-directory: ./abi/edge
  runtime:
    needs: edge
    runs-on: self-hosted
    steps:
      - name: Make ABI Runtime Image
        run: zsh -x make-runtime-image.sh
        working-directory: ./abi/runtime
  go:
    needs: edge
    runs-on: self-hosted
    steps:
      - name: Make Go Image
        run: zsh -x make-go-image.sh
        working-directory: ./go
  jdk:
    needs: edge
    runs-on: self-hosted
    steps:
      - name: Make JDK Image
        run: zsh -x make-jdk-image.sh
        working-directory: ./java/17/jdk
  jre:
    needs: edge
    runs-on: self-hosted
    steps:
      - name: Make JRE Image
        run: zsh -x make-jre-image.sh
        working-directory: ./java/17/jre
